# This workflow will build a docker image and publish it to the docker repository with the updated codes

name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Trigger workflow when changes are pushed to the main branch
  pull_request:
    branches: [ "main" ] # Optionally trigger on pull requests

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      # Checkout the repository
      #- name: Checkout Code
      #  uses: actions/checkout@v3

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lda-topic-modeling-app:latest

      # Log in to Docker Hub
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }} # Docker Hub username stored as a secret
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub password stored as a secret
          
      # Set up Docker Buildx
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/lda-topic-modeling-app:latest
